# Generated by Django 5.1.6 on 2025-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
