# Generated by Django 5.1.6 on 2025-03-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titie',
            new_name='title',
        ),
    ]
